// <auto-generated />
using DAY1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAY1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226202831_UserModelAdded")]
    partial class UserModelAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAY1.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CostPrice = 50000m,
                            Name = "Laptop",
                            SellPrice = 60000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CostPrice = 15000m,
                            Name = "Mobile",
                            SellPrice = 20000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CostPrice = 2000m,
                            Name = "Headphones",
                            SellPrice = 3000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = "Furniture",
                            CostPrice = 1800m,
                            Name = "Chair",
                            SellPrice = 2500m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Furniture",
                            CostPrice = 5000m,
                            Name = "Table",
                            SellPrice = 7000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            CostPrice = 20000m,
                            Name = "Sofa",
                            SellPrice = 25000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "Stationery",
                            CostPrice = 60m,
                            Name = "Notebook",
                            SellPrice = 100m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 8,
                            Category = "Stationery",
                            CostPrice = 10m,
                            Name = "Pen",
                            SellPrice = 20m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 9,
                            Category = "Stationery",
                            CostPrice = 20m,
                            Name = "Marker",
                            SellPrice = 40m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothing",
                            CostPrice = 500m,
                            Name = "T-Shirt",
                            SellPrice = 800m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothing",
                            CostPrice = 1400m,
                            Name = "Jeans",
                            SellPrice = 2000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothing",
                            CostPrice = 2500m,
                            Name = "Jacket",
                            SellPrice = 3500m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accessories",
                            CostPrice = 250m,
                            Name = "Water Bottle",
                            SellPrice = 400m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accessories",
                            CostPrice = 800m,
                            Name = "Backpack",
                            SellPrice = 1200m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accessories",
                            CostPrice = 3500m,
                            Name = "Watch",
                            SellPrice = 5000m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("DAY1.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
