// <auto-generated />
using DAY1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAY1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224165130_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAY1.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Name = "WashingMachine"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Name = "TV"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Clothing",
                            Name = "Tshirt"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Clothing",
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Clothing",
                            Name = "Jacket"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Food",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Food",
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Food",
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sports",
                            Name = "Bat"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sports",
                            Name = "Ball"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sports",
                            Name = "Racket"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
