// <auto-generated />
using System;
using CTMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CTMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221073715_ModelAdded")]
    partial class ModelAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CTMS.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepName = "IT",
                            Location = "Ahmedabad"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepName = "HR",
                            Location = "Gandhinagar"
                        });
                });

            modelBuilder.Entity("CTMS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Email = "ashish123@gmail.com",
                            Name = "Ashish Pateliya",
                            Salary = 120000.0
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Email = "raju123@gmail.com",
                            Name = "Raj Rana",
                            Salary = 50000.0
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 2,
                            Email = "nitya123@gmail.com",
                            Name = "Nitya Shah",
                            Salary = 40000.0
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 1,
                            Email = "mihir123@gmail.com",
                            Name = "Mihir Prajapati",
                            Salary = 30000.0
                        });
                });

            modelBuilder.Entity("CTMS.Models.EmployeeTrainer", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ExpertiseLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeTrainers");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            ExpertiseLevel = "Expert"
                        },
                        new
                        {
                            EmployeeId = 4,
                            ExpertiseLevel = "Beginner"
                        });
                });

            modelBuilder.Entity("CTMS.Models.Enrollment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollDate")
                        .HasColumnType("date");

                    b.Property<int>("PerformanceScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("EmployeeId", "TrainingProgramId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasCheckConstraint("CK_Enrollment_PerformanceScore", "PerformanceScore >= 0 AND PerformanceScore <= 100");
                        });

                    b.HasData(
                        new
                        {
                            EmployeeId = 2,
                            TrainingProgramId = 2,
                            EnrollDate = new DateOnly(2026, 10, 2),
                            PerformanceScore = 0
                        });
                });

            modelBuilder.Entity("CTMS.Models.TrainingProgram", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingProgramId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("TrainingProgramId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingPrograms");

                    b.HasData(
                        new
                        {
                            TrainingProgramId = 1,
                            Duration = 50,
                            StartDate = new DateOnly(2026, 1, 5),
                            Title = "Data Science",
                            TrainerId = 4
                        },
                        new
                        {
                            TrainingProgramId = 2,
                            Duration = 30,
                            StartDate = new DateOnly(2026, 2, 5),
                            Title = "C#",
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("CTMS.Models.Employee", b =>
                {
                    b.HasOne("CTMS.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CTMS.Models.EmployeeTrainer", b =>
                {
                    b.HasOne("CTMS.Models.Employee", "Employee")
                        .WithOne("EmployeeTrainer")
                        .HasForeignKey("CTMS.Models.EmployeeTrainer", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CTMS.Models.Enrollment", b =>
                {
                    b.HasOne("CTMS.Models.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CTMS.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("CTMS.Models.TrainingProgram", b =>
                {
                    b.HasOne("CTMS.Models.EmployeeTrainer", "Trainer")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("CTMS.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CTMS.Models.Employee", b =>
                {
                    b.Navigation("EmployeeTrainer");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CTMS.Models.EmployeeTrainer", b =>
                {
                    b.Navigation("TrainingPrograms");
                });

            modelBuilder.Entity("CTMS.Models.TrainingProgram", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
